### ISSUE TITLE
self.pw_bn_layer should have nothing to do with the stride

### ISSUE THREAD

**Issue by gaozhun** [notplus/MobileOne-TF2#1]
```
            self.pw_bn_layer = layers.BatchNormalization(
            ) if out_channels == in_channels and stride == 1 else None

There is an error on line 69. The self.pw_bn_layer should have nothing to do with the stride

**Comment by notplus** [comment]
Suppose `out_channels != in_channels or stride != 1`, the output of pointwise conv's size will be changed which can not apply a BN layer.

**Comment by gaozhun** [comment]
but this stride is not pointwise conv's stride

**Comment by notplus** [comment]
You're right, I will fix it.

**Comment by gaozhun** [comment]
Similarly, the DW_BN_layer in line 62 should be independent of out_channels and IN_channels because the number of input and output channels in DW is always the same
