### ISSUE TITLE
about quantization

### ISSUE THREAD

**Issue by james77777778** [notplus/MobileOne-TF2#2]
Hi @notplus 
Thank you for your great work. I want to try MobileOne in TF but I'm wondering about quantization for MobileOne.
(I have read that re-parameterization technique needs some extra work to have a good quantization result...)

Do you try QAT or PQT with this work?
Does the performance remain?

Thanks!

**Comment by notplus** [comment]
Hi, I tried QAT to keep the int8 accuracy, and it looks like good for my keypoint regression task. But it was being used in MobileNet architecture which contains MobileOne blocks. I am not sure if MobileOne is OK. Maybe it's because MobileOne doesn't perform well that I don't use it.

**Comment by james77777778** [comment]
> Hi, I tried QAT to keep the int8 accuracy, and it looks like good for my keypoint regression task. But it was being used in MobileNet architecture which contains MobileOne blocks. I am not sure if MobileOne is OK. Maybe it's because MobileOne doesn't perform well that I don't use it.

I might give it a try! Thanks for your information.
